sqlite: &sqlite
  adapter: sqlite3
  database: db/test.sqlite3

mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: has_accounts_test

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: has_accounts_test

test:
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || 'sqlite' %>
